name: 'demo_project'
version: '1.0.0'
config-version: 2

profile: 'demo_project'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
    - "logs"

seeds:
  demo_project:
    +schema: raw_data
    +quote_columns: true

models:
  demo_project:
